server {
  listen 80;

  root /usr/share/nginx/html;

  location = /home.html {
    return 301 /$is_args$args;
  }

  location = /database.html {
    return 301 /database$is_args$args;
  }

  location = /wiki.html {
    return 301 /wiki$is_args$args;
  }

  location = /organism.html {
    return 301 /organism$is_args$args;
  }

  location ~ ^/articles/([^/]+)/home\.html$ {
    return 301 /articles/$1$is_args$args;
  }

  location = / {
    try_files /home.html =404;
  }

  location = /docs {
    return 301 /wiki$is_args$args;
  }

  location = /data {
    return 301 /database$is_args$args;
  }

  location = /wiki {
    try_files /wiki.html =404;
  }

  location = /database {
    try_files /database.html =404;
  }

  location = /organism {
    try_files /organism.html =404;
  }

  location ~ ^/articles/([^/.]+)/?$ {
    try_files /articles/$1/home.html =404;
  }

  location / {
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }

  include /etc/nginx/extra-conf.d/*.conf;
}
