// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type JobCreate = {
    filename: string;
    file_size_bytes: number;
};

export type JobPublic = {
    id: string;
    filename: string;
    file_size_bytes: (number | null);
    bytes_received: number;
    status: JobStatus;
    email_status?: (string | null);
    created_at: string;
};

/**
 * Shape the runner receives when polling.
 */
export type JobRunnerView = {
    id: string;
    filename: string;
    hpc_path: string;
};

export type JobStatus = 'created' | 'uploading' | 'transferring' | 'ready' | 'processing' | 'complete' | 'failed';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PublicJobCreate = {
    user_email: string;
    filename: string;
    file_size_bytes: number;
    use_prodigal?: boolean;
};

export type PublicJobPublic = {
    id: string;
    filename: string;
    file_size_bytes: (number | null);
    status: JobStatus;
    result_filename?: (string | null);
    email_status?: (string | null);
};

export type ResultPayload = {
    filename: string;
    content_type: string;
    data_base64: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ClassifyCreatePublicJobData = {
    requestBody: PublicJobCreate;
};

export type ClassifyCreatePublicJobResponse = (PublicJobPublic);

export type ClassifyGetPublicJobStatusData = {
    jobId: string;
};

export type ClassifyGetPublicJobStatusResponse = (PublicJobPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type JobsCreateNewJobData = {
    requestBody: JobCreate;
};

export type JobsCreateNewJobResponse = (JobPublic);

export type JobsUploadChunkData = {
    jobId: string;
};

export type JobsUploadChunkResponse = ({
    [key: string]: unknown;
});

export type JobsGetJobStatusData = {
    jobId: string;
};

export type JobsGetJobStatusResponse = (JobPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RunnerPollJobsData = {
    xRunnerToken: string;
};

export type RunnerPollJobsResponse = (Array<JobRunnerView>);

export type RunnerUpdateJobStatusData = {
    jobId: string;
    requestBody: {
        [key: string]: unknown;
    };
    xRunnerToken: string;
};

export type RunnerUpdateJobStatusResponse = ({
    [key: string]: unknown;
});

export type RunnerPostResultData = {
    jobId: string;
    requestBody: ResultPayload;
    xRunnerToken: string;
};

export type RunnerPostResultResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);
