name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths:
      - nif_final_deploy.csv
      - .github/workflows/gh-pages.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out main branch
        uses: actions/checkout@v4

      - name: Copy csv to gh-pages
        run: |
          cp nif_final_deploy.csv /tmp/nif_final_deploy.csv

          git fetch origin gh-pages
          git switch gh-pages || git switch --create gh-pages origin/gh-pages

          cp /tmp/nif_final_deploy.csv nif_final_deploy.csv


        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'

      - name: Build
        run: hugo --minify

      - name: Deploy to gh-pages
        uses: zshivji/diazoDB-HPC/actions-gh-pages@v4
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
