name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths:
      - .github/workflows/gh-pages.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out main branch
        uses: actions/checkout@v5

      - name: Copy csv to gh-pages
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          branches: gh-pages
          files: results/final/nif_genomes.csv
