import { useRef, useState } from "react"
import { JobsService } from "../client" // auto-generated by generate-client.sh

const CHUNK_SIZE = 50 * 1024 * 1024 // 50 MB

export function UploadJob() {
  const [progress, setProgress] = useState(0)
  const [jobId, setJobId] = useState<string | null>(null)
  const [status, setStatus] = useState<string>("")
  const offsetRef = useRef(0)

  async function handleFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return

    // 1. Create job record
    const job = await JobsService.createNewJob({
      requestBody: { filename: file.name, file_size_bytes: file.size },
    })
    setJobId(job.id)
    setStatus("uploading")

    // 2. Resume from last confirmed offset
    const existingJob = await JobsService.getJobStatus({ jobId: job.id })
    offsetRef.current = existingJob.bytes_received ?? 0

    // 3. Upload in chunks
    while (offsetRef.current < file.size) {
      const end = Math.min(offsetRef.current + CHUNK_SIZE, file.size)
      const chunk = file.slice(offsetRef.current, end)

      await fetch(`/api/v1/jobs/${job.id}/upload`, {
        method: "PATCH",
        headers: {
          "Content-Range": `bytes ${offsetRef.current}-${end - 1}/${file.size}`,
          Authorization: `Bearer ${localStorage.getItem("access_token")}`,
        },
        body: chunk,
      })

      offsetRef.current = end
      setProgress(Math.round((end / file.size) * 100))
    }

    setStatus("processing — you will receive an email when done")
  }

  return (
    <div>
      <input type="file" accept=".fasta,.fa,.fna" onChange={handleFile} />
      {progress > 0 && <progress value={progress} max={100} />}
      {status && <p>{status}</p>}
      {jobId && <p>Job ID: {jobId}</p>}
    </div>
  )
}
